modLoader = "javafml"
loaderVersion = "[39,)"
license="https://gist.github.com/JTK222/b85b336bfae5c29e796d0934894aca3e#file-dark-roleplay-mod-license-v1-md"

[[mods]]
modId="clientcommands"
version = "1.3"
displayName="Client Commands"
displayURL="https://www.curseforge.com/minecraft/mc-mods/client-commands"
#logoFile="examplemod.png" #optional
credits="Lead Programmer: JTK222, 1.18 Port: PORTB"
authors="JTK222"
description='''
Client Commands is a tiny utility mod/library,
which allows other mods to easily register client side commands.
And also provides auto completion for them in the chat.
The default prefix for client side commands is !'''

[[dependencies.clientcommands]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clientcommands]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"
