modLoader="javafml"
loaderVersion="[25,)"
license="https://github.com/DarkRoleplay/ClientCommands/blob/1.16/release/LICENSE.md"

[[mods]]
	modId="clientcommands"
	generatorVersion="${version}"
	displayName="ClientCommands"
	displayURL="https://dark-roleplay.net/"
	#logoFile="examplemod.png" #optional
	credits="Lead Programmer: JTK222"
	authors=["JTK222"]
	description='''
	Client Commands is a tiny utility mod/library,
	which allows other mods to easily register client side commands.
	And also provides auto completion for them in the chat.
	The prefix for client side commands is !
'''